 export const dataTest = () => {

  return {data: data}
 }



 const data = [
  {
    id: "01",
    name: "Franz Kafka",
    firstName: "Franz",
    secondName: "Kafka",
    email: "franzkafka@mail.com",
    country: "Czech Republic",
    code: "+34",
    number: "4235678912",
    suscribed: true,
    address: "test",
  },
  {
    id: "02",
    name: "aldous huxley",
    firstName: "aldous",
    secondName: "huxley",
    email: "aldoushuxley@mail.com",
    country: "Emgland",
    code: "+24",
    number: "4235678912",
    suscribed: false,
    address: "test",
  },
  {
    id: "03",
    name: "Margaret Yourcenar",
    firstName: "Margaret",
    secondName: "Yourcenar",
    email: "margaretyourcenar@mail.com",
    country: "France",
    code: "+31",
    number: "4235678912",
    suscribed: true,
    address: "test",
  },

  {
    id: "04",
    name: "Marie curie",
    firstName: "Marie",
    secondName: "curie",
    email: "Mariecurie@mail.com",
    country: "Poland",
    code: "+21",
    number: "4235672912",
    suscribed: true,
    address: "test",
  },

  {
    id: "05",
    name: "Charles bukowski",
    firstName: "Charles",
    secondName: "bukowski",
    email: "Charlesbukowski@mail.com",
    country: "EEUU",
    code: "+01",
    number: "4235678912",
    suscribed: false,
    address: "test",
  },

  {
    id: "06",
    name: "daniel Defoe",
    firstName: "daniel",
    secondName: "Defoe",
    email: "danielDefoe@mail.com",
    country: "France",
    code: "+283",
    number: "4235678912",
    suscribed: true,
    address: "test",
  },
  {
    id: "07",
    name: "Fredrick nietzsche",
    firstName: "Fredrick",
    secondName: "nietzsche",
    email: "Fredricknietzsche@mail.com",
    country: "Germany",
    code: "+31",
    number: "4235678912",
    suscribed: false,
    address: "test",
  },

  {
    id: "08",
    name: "Martin Luther",
    firstName: "Martin",
    secondName: "Luther",
    email: "MartinLuther@mail.com",
    country: "Germany",
    code: "+21",
    number: "4235678912",
    suscribed: true,
    address: "test",
  },

  {
    id: "09",
    name: "pedro aznar",
    firstName: "pedro",
    secondName: "aznar",
    email: "pedroaznar@mail.com",
    country: "France",
    code: "+31",
    number: "4235678912",
    suscribed: true,
    address: "test",
  },

  {
    id: "10",
    name: "mercedes sosa",
    firstName: "mercedes",
    secondName: "sosa",
    email: "mercedessosa@mail.com",
    country: "Uruguay",
    code: "+57",
    number: "4235678912",
    suscribed: false,
    address: "test",
  },

  {
    id: "11",
    name: "Miguel Hernandez",
    firstName: "Miguel",
    secondName: "Hernandez",
    email: "MiguelHernandez@mail.com",
    country: "France",
    code: "+31",
    number: "4235678912",
    suscribed: true,
    address: "test",
  },

  {
    id: "12",
    name: "Ringo Star",
    firstName: "Ringo",
    secondName: "Star",
    email: "RingoStar@mail.com",
    country: "England",
    code: "+12",
    number: "4235678912",
    suscribed: true,
    address: "test",
  },

  {
    id: "13",
    name: "william shakespeare",
    firstName: "william",
    secondName: "shakespeare",
    email: "williamshakespeare@mail.com",
    country: "France",
    code: "+31",
    number: "4235678912",
    suscribed: true,
    address: "test",
  },
  {
    id: "14",
    name: "Miguel de Cervantes",
    firstName: "Miguel",
    secondName: "de Cervantes",
    email: "MigueldeCervantes@mail.com",
    country: "France",
    code: "+31",
    number: "4235678912",
    suscribed: true,
    address: "test",
  },

  {
    id: "15",
    name: "Christopher nolan",
    firstName: "Christopher",
    secondName: "nolan",
    email: "Christophernolan@mail.com",
    country: "France",
    code: "+1",
    number: "4235678912",
    suscribed: true,
    address: "test",
  },

  {
    id: "16",
    name: "pablo Bermudez",
    firstName: "pablo",
    secondName: "Bermudez",
    email: "pabloBermudez@mail.com",
    country: "France",
    code: "+58",
    number: "4235678912",
    suscribed: true,
    address: "test",
  },

  {
    id: "17",
    name: "Bruno diaz",
    firstName: "Bruno",
    secondName: "diaz",
    email: "Brunodiaz@mail.com",
    country: "France",
    code: "+31",
    number: "4235678912",
    suscribed: true,
    address: "test",
  },
  {
    id: "18",
    name: "Ricardo Tapia",
    firstName: "Ricardo",
    secondName: "Tapia",
    email: "RicardoTapia@mail.com",
    country: "France",
    code: "+3",
    number: "4235678912",
    suscribed: true,
    address: "test",
  },
  {
    id: "19",
    name: "maria melendez",
    firstName: "maria",
    secondName: "melendez",
    email: "mariamelendez@mail.com",
    country: "France",
    code: "+31",
    number: "4235678912",
    suscribed: true,
    address: "test",
  },
  {
    id: "20",
    name: "juan perez",
    firstName: "juan",
    secondName: "perez",
    email: "juanperez@mail.com",
    country: "France",
    code: "+31",
    number: "4235678912",
    suscribed: true,
    address: "test",
  },

  {
    id: "21",
    name: "Alfred hotchcock",
    firstName: "alfred",
    secondName: "hotchcock",
    email: "alfredhotchcock@mail.com",
    country: "France",
    code: "+31",
    number: "4235678912",
    suscribed: true,
    address: "test",
  },

  {
    id: "22",
    name: "Reitner Rilke",
    firstName: "Reitner",
    secondName: "Rilke",
    email: "ReitnerRilke@mail.com",
    country: "France",
    code: "+31",
    number: "4235678912",
    suscribed: true,
    address: "test",
  },

  {
    id: "23",
    name: "Hugo gonzales",
    firstName: "Hugo",
    secondName: "gonzales",
    email: "Hugogonzales@mail.com",
    country: "holanda",
    code: "+3",
    number: "4235678912",
    suscribed: true,
    address: "test",
  },

  {
    id: "24",
    name: "carlos fuentes",
    firstName: "carlos",
    secondName: "fuentes",
    email: "carlosfuentes@mail.com",
    country: "France",
    code: "+31",
    number: "4235678912",
    suscribed: true,
    address: "test",
  },
  {
    id: "25",
    name: "Nick cave",
    firstName: "Nick",
    secondName: "cave",
    email: "Nickcave@mail.com",
    country: "France",
    code: "+31",
    number: "4235678912",
    suscribed: true,
    address: "test",
  },
  {
    id: "26",
    name: "Pedro perez",
    firstName: "Pedro",
    secondName: "perez",
    email: "Pedroperez@mail.com",
    country: "France",
    code: "+31",
    number: "4235678912",
    suscribed: true,
    address: "test",
  },
  {
    id: "27",
    name: "Elio reims",
    firstName: "Elio",
    secondName: "reims",
    email: "Elioreims@mail.com",
    country: "France",
    code: "+31",
    number: "4235678912",
    suscribed: true,
    address: "test",
  },
];
